# Generated by Django 3.0.7 on 2020-06-30 22:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('iin', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='IIN has to be 12 digits', regex='^[\\d]{12}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('iin', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='IIN has to be 12 digits', regex='^[\\d]{12}$')])),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditProgramm',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('minimum_loan_amount', models.PositiveIntegerField()),
                ('maximum_loan_amount', models.PositiveIntegerField()),
                ('minimum_borrower_age', models.PositiveIntegerField()),
                ('maximum_borrower_age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('rejected', 'rejected'), ('approved', 'approved')], max_length=30)),
                ('rejection_cause', models.CharField(blank=True, max_length=256, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit_applications', to='credit_application.Borrower')),
                ('credit_programm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit_applications', to='credit_application.CreditProgramm')),
            ],
        ),
    ]
