# Generated by Django 3.0.7 on 2020-07-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creditapplication',
            unique_together={('borrower', 'credit_programm', 'loan_amount')},
        ),
    ]
